version: '3.8'

services:
  influxdb:
    image: influxdb:2.7.1-alpine
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    ports:
      - '8086:8086'
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8086/ping" ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - stock_market_network

  grafana:
    image: grafana/grafana:9.5.3
    container_name: grafana-server
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - '3000:3000'
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:3000/api/health" ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - stock_market_network

networks:
  stock_market_network:
    name: stock_market_network
    driver: bridge

volumes:
  grafana_data: { }
  influxdb_data: { }